---
title: "Differential Equations Solving"
author: "Michael Liou"
date: "4/20/2022"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(deSolve)
```


# ODE Solver

Using `ode` from package deSolve

```{r}
LVmod <- function(Time, State, Pars) {
  with(as.list(c(State, Pars)), {
    Ingestion    <- rIng  * Prey * Predator #  \beta x y
    GrowthPrey   <- rGrow * Prey * (1 - Prey/K) # \alpha x
    MortPredator <- rMort * Predator

    dPrey        <- GrowthPrey - Ingestion
    dPredator    <- Ingestion * assEff - MortPredator

    return(list(c(dPrey, dPredator)))
  })
}

pars  <- c(rIng   = 0.2,    # /day, rate of ingestion
           rGrow  = 1.0,    # /day, growth rate of prey
           rMort  = 0.2 ,   # /day, mortality rate of predator
           assEff = 0.5,    # -, assimilation efficiency
           K      = 10)     # mmol/m3, carrying capacity

yini  <- c(Prey = 1, Predator = 2) # initial states of the system
times <- seq(0, 200, by = 1) # initial time
out   <- ode(yini, times, LVmod, pars)
summary(out)

## Default plot method
plot(out)

## User specified plotting
matplot(out[ , 1], out[ , 2:3], type = "l", xlab = "time", ylab = "Conc",
        main = "Lotka-Volterra", lwd = 2)
legend("topright", c("prey", "predator"), col = 1:2, lty = 1:2)
```


```{r}
SPCmod <- function(t, x, parms, input)  {
  with(as.list(c(parms, x)), {
    import <- input(t)
    dS <- import - b*S*P + g*C    # substrate
    dP <- c*S*P  - d*C*P          # producer
    dC <- e*P*C  - f*C            # consumer
    res <- c(dS, dP, dC)
    list(res)
  })
}

## The parameters 
parms <- c(b = 0.001, c = 0.1, d = 0.1, e = 0.1, f = 0.1, g = 0.0)

## vector of timesteps
times <- seq(0, 200, length = 101)

## external signal with rectangle impulse
signal <- data.frame(times = times,
                     import = rep(0, length(times)))

signal$import[signal$times >= 10 & signal$times <= 11] <- 0.2

sigimp <- approxfun(signal$times, signal$import, rule = 2)

## Start values for steady state
xstart <- c(S = 1, P = 1, C = 1)

## Solve model
out <- ode(y = xstart, times = times,
           func = SPCmod, parms = parms, input = sigimp)

## Default plot method
plot(out)

## User specified plotting
mf <- par(mfrow = c(1, 2))
matplot(out[,1], out[,2:4], type = "l", xlab = "time", ylab = "state")
legend("topright", col = 1:3, lty = 1:3, legend = c("S", "P", "C"))
plot(out[,"P"], out[,"C"], type = "l", lwd = 2, xlab = "producer",
  ylab = "consumer")
par(mfrow = mf)
```

### SIR Modeling

A simple example is provided by https://www.r-bloggers.com/2017/01/sir-model-with-desolve-ggplot2/


```{r}
SIRmod <- function(Time, State, Pars) {
  with(as.list(c(State, Pars)), {
    dSusceptible <- -beta * Infected * Susceptible
    dInfected <- beta * Infected * Susceptible - gamma * Infected
    dRecovered <- gamma * Infected
    return(list(c(dSusceptible, dInfected, dRecovered)))
  })
}

pars  <- c(beta = 1.5,
           gamma = .3)     # mmol/m3, carrying capacity

yini  <- c(Susceptible = 1-1e-6, Infected = 1e-6, Recovered = 0) # initial states of the system
times <- seq(0, 100 , by = 1) # initial time
out   <- ode(yini, times, SIRmod, pars)
summary(out)

sir_diffeq <- function(Time, State, Pars) {
  with(as.list(c(State, Pars)), {
    dSusceptible <- -beta * Infected * Susceptible
    dInfected <- beta * Infected * Susceptible - gamma * Infected
    dRecovered <- gamma * Infected
    return(list(c(dSusceptible, dInfected, dRecovered)))
  })
}

sir_ode <- function(beta = 1, gamma = .2,
                initial_state = c(Susceptible = 1-1e-6,
                                  Infected = 1e-6,
                                  Recovered = 0),
                times = seq(0, 100, by = 1)) {
  pars <- c(beta = beta, gamma = gamma)
  
  # check that initial state has the correctly named variables
  ode(initial_state, times, sir_diffeq, pars)
}

beta <- 1
gamma <- .2
out <- sir_ode(beta = beta, gamma = gamma)

out %>% as.data.frame() %>%
  pivot_longer(Susceptible:Recovered, names_to = "state", values_to = "prop") %>% 
  ggplot(aes(time, prop)) + 
  geom_line(aes(color = state)) +
  theme_minimal() + 
  labs(title = sprintf("SIR, beta = %g, gamma = %g", beta, gamma))
```




