---
title: "Colors in R"
editor: visual
---

## Viewing Color Palettes

```{r}
library(RColorBrewer)
```

```{r}
hcl.pals(type = "sequential")
hcl.colors(256, palette = "ag_sunset")

plot(0, 
     type = "n",
     axes = F,
     xlab = "", ylab = "",
     xlim = c(0, 1),
     ylim = c(0, 1),
     xaxs = "i",
     yaxs = "i",
     omi = rep(0, 4),
     oma = rep(0, 4),
     mar = rep(0, 4),
     frame.plot = F)
rect(0, .5, .8, 1, col = terrain.colors(256))
library(grid)
grid.newpage()
grid.raster(1:10)
redGradient <- matrix(hcl(0, 80, seq(50, 80, 10)),
                      nrow=4, ncol=5)
# interpolated
grid.newpage()
plot(raster(I), breaks = hist(I, breaks = 100, plot = F)$breaks, col = hcl.colors(101, palette = "ag_sunset"),
     interpolate = T)
grid.raster(I)

library(signal)
library(pracma)
x <- seq(-1, 1, length.out = 11)
y <- seq(-1, 1, length.out = 11)
Z <- outer(x, y, {\(x, y) x^2 + y^2})
xp <- yp <- 


# try upsampling
interp2(x, y, Z, xp, yp, "linear")

# mgrid <- meshgrid(x, y)
# X <- mgrid$X
# Y <- mgrid$Y
# Z <- X^2 + Y^2

library(plot3D)
library(plotly)
fig <- plot_ly(z=~Z) |> add_surface()

config(fig, displaylogo = FALSE, scrollZoom = FALSE)
  
persp(z = Z, theta = 30, phi = 30, col = hcl.colors(250)[], shade = NA)






```
