# project:
  # output-dir: _output
project:
  type: book

book:
  title: "Personal Documentation"
  author: "Michael Liou"
  date: "11/14/2022"
  chapters:
    - "index.qmd"
    - "matrix/matrix.qmd"
    - "stochastic/stochastic.qmd"
    - "meta/meta.qmd"
    - "color/color.qmd"

author: "Michael Liou"
toc: true
toc-depth: 3
format:
  html:
    mainfont: Palitino
    code-fold: true
    theme: lumen
    linestretch: 1.2
    fontsize: 1em
    html-math-method: katex

execute:
  cache: true
  freeze: true

bibliography: references.bib
