# project:
  # output-dir: _output
project:
  type: book
  output-dir: ../mydocs/eac32f09bcb48f97d5f71044b5c8eac7b4bfadc1

book:
  title: "Personal Documentation"
  author: "Michael Liou"
  date: "11/14/2022"
  search:
    location: navbar
    type: overlay
  chapters:
    - "index.qmd"
    - "advanced/advanced.qmd"
    - "approximation/approximation.qmd"
    - "bayesian/bayesian.qmd"
    - "categorical/categorical.qmd"
    - "changepoint/changepoint.qmd"
    - "chaos/chaos.qmd"
    - "crossover/crossover.qmd"
    - "diffeq/diffeq.qmd"
    - "epidemiology/epidemiology.qmd"
    - "experimentaldesign/experimentaldesign.qmd"
    - "exponential/exponential.qmd"
    - "gam/gam.qmd"
    - "longitudinal/longitudinal.qmd"
    - "longitudinal/randomcoef.qmd"
    - "longitudinal/within_between.qmd"
    - "matrix/matrix.qmd"
    - "meta/meta.qmd"
    - "mixed/mixed.qmd"
    - "mixed/mixed_variance.qmd"
    - "network/network_centrality.qmd"
    - "network/network_gnar.qmd"
    - "next_gen_sequencing/next_gen_sequencing.qmd"
    - "nonlinear/nonlinear.qmd"
    - "observable/observable.qmd"
    - "optimization/optimization.qmd"
    - "ordination/ordination.qmd"
    - "parallel/parallel.qmd"
    - "plant_breeding/plant_breeding.qmd"
    - "social_network/social_network.qmd"
    - "spatial/carbayes.qmd"
    - "spatial/spatial.qmd"
    - "stochastic/stochastic.qmd"
    - "stochastic/ctmc.qmd"
    - "timeseries/timeseries.qmd"
    - part: "Draft"
      chapters:
        - "bootstrap/bootstrap.qmd"
        - "causal/causal.qmd"
        - "sensitivity/sensitivity.qmd"
        - "signal/signal.qmd"
  appendices:
    - "color/color.qmd"

author: "Michael Liou"
toc: true
toc-depth: 3
number-depth: 3
format:
  html:
    mainfont: Palitino
    code-fold: true
    theme: lumen
    linestretch: 1.2
    fontsize: 1em
    html-math-method: katex

execute:
  cache: true
  freeze: auto

bibliography: references.bib
