# project:
  # output-dir: _output
project:
  type: book
  output-dir: ../mydocs/eac32f09bcb48f97d5f71044b5c8eac7b4bfadc1

book:
  title: "Personal Documentation"
  author: "Michael Liou"
  date: "11/14/2022"
  search:
    location: navbar
    type: overlay
  chapters:
    - "index.qmd"
    - "matrix/matrix.qmd"
    - "stochastic/stochastic.qmd"
    - "meta/meta.qmd"
    - part: "From Informational"
      chapters:
        - "bootstrap/bootstrap.qmd"
        - "causal/causal.qmd"
  appendices:
    - "color/color.qmd"

author: "Michael Liou"
toc: true
toc-depth: 3
number-depth: 3
format:
  html:
    mainfont: Palitino
    code-fold: true
    theme: lumen
    linestretch: 1.2
    fontsize: 1em
    html-math-method: katex

execute:
  cache: true
  freeze: auto

bibliography: references.bib
